defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password:

production:
  <<: *defaults
  host: localhost
  database: adtrex_production

development:
  <<: *defaults
  database: adtrex_dev

test:
  <<: *defaults
  database:  adtrex_test
